source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'dotenv-rails'
gem 'heartwood-decorator', path: File.expand_path('../../', __dir__)
gem 'pry'
gem 'rspec-rails'
gem 'sqlite3'
